#include<bits/stdc++.h>
using namespace std;
int main()
{
    ios_base::sync_with_stdio(false);
    int n,k,a[100000],i,j,b=0,c=0,d,e,f,g,h;
    cin>>n>>k;
    for(i=1;i<=n;i++)
    {
        cin>>a[i];
    }
    for(i=1;i<=n;i++)
    {
        if(a[i]>100)
        {
            continue;
        }
        for(j=i+1;j<=n;j++)
        {
            if(a[j]>100)
            {
                continue;
            }
            if(a[i]==a[j])
            {
                a[j]=a[j]+100;
            }
        }
    }
    for(i=1;i<=n;i++)
    {
        if(a[i]<=100)
        {
            b++;
        }
    }
    if(b<k)
    {
        cout<<"NO"<<endl;
    }
    else{
        cout<<"YES"<<endl;
        for(i=1;i<=n;i++)
        {
            if(k==c)
            {
                break;
            }
            if(a[i]<=100)
            {
                cout<<i<<" ";
                c++;
            }
        }
    }
}
