#include<bits/stdc++.h>
using namespace std;
int main()
{
    ios_base::sync_with_stdio(false);
    int n,a[100000],i,j,b=0,c=0,d,e,f,g,h;
    cin>>n;
    for(i=0;i<n;i++)
    {
        cin>>a[i];
        if(a[i]==5)
        {
            b++;
        }
        else{
            c++;
        }
    }
    if(c==0)
    {
        cout<<-1;
    }
    else{
        d=b/9;
        if(d==0)
        {
            cout<<0;
        }
        else{
            for(i=0;i<d*9;i++)
            {
                cout<<5;
            }
            for(i=0;i<c;i++)
            {
                cout<<0;
            }
        }
    }
}
