#include<bits/stdc++.h>
using namespace std;
int main()
{
    ios_base::sync_with_stdio(false);
    int t,n,m,i,j,a,b=0,c=0,d=0,e=0,f,g,h;
    cin>>t;
    while(t--)
    {
        cin>>n>>m;
        if((n*m)%2!=0)
        {
            for(i=1;i<=n;i++)
            {
                if(i%2!=0)
                {
                    for(j=1;j<=m;j++)
                    {
                        if(b==0)
                        {
                            cout<<"B";
                            b=1;
                        }
                        else{
                            cout<<"W";
                            b=0;
                        }
                    }
                    cout<<endl;
                    b=0;
                }
                else{
                    for(j=1;j<=m;j++)
                    {
                        if(b==0)
                        {
                            cout<<"W";
                            b=1;
                        }
                        else{
                            cout<<"B";
                            b=0;
                        }
                    }
                    cout<<endl;
                    b=0;
                }
            }
        }
        else{
            for(i=1;i<=1;i++)
            {
                cout<<"B";
                for(j=2;j<=m;j++)
                {
                    if(c==0)
                    {
                        cout<<"B";
                        c=1;
                    }
                    else{
                        cout<<"W";
                        c=0;
                    }
                }
            }
            cout<<endl;
            c=0;
            for(i=2;i<=n;i++)
            {
                if(i%2==0)
                {
                    for(j=1;j<=m;j++)
                    {
                        if(c==0)
                        {
                            cout<<"B";
                            c=1;
                        }
                        else{
                            cout<<"W";
                            c=0;
                        }
                    }
                    cout<<endl;
                    c=0;
                }
                else{
                    for(j=1;j<=m;j++)
                    {
                        if(c==0)
                        {
                            cout<<"W";
                            c=1;
                        }
                        else{
                            cout<<"B";
                            c=0;
                        }
                    }
                    cout<<endl;
                    c=0;
                }
            }
        }
        b=0;c=0;
    }
}
